### ISSUE TITLE
Unify class names of restart variants

### ISSUE THREAD

**Issue by MartinWolke** [jakobbossek/salesperson#28]
The class names of [LKH-Restart](https://github.com/jakobbossek/salesperson/blob/f6f097fa8d73c8379641280563c21f508a742c91/R/solver.lkh_restart.R#L4) and [EAX-Restart](https://github.com/jakobbossek/salesperson/blob/f6f097fa8d73c8379641280563c21f508a742c91/R/solver.eax_restart.R#L4) (cl-Attribute) differ from the default names in  [solverPaths](https://github.com/jakobbossek/salesperson/blob/f6f097fa8d73c8379641280563c21f508a742c91/R/solverPaths.R#L21) leading to an error when these solvers are started (the [solver$bin](https://github.com/jakobbossek/salesperson/blob/f6f097fa8d73c8379641280563c21f508a742c91/R/makeSolver.R#L13) argument cannot be created successfully).

**Comment by jakobbossek** [comment]
Done.
