### ISSUE TITLE
Add Pihera and Musliu features

### ISSUE THREAD

**Issue by jakobbossek** [jakobbossek/salesperson#36]
Since these are implemented in C# and one needs to use the mono compiler on unix systems, which is a pain in the a*\* we need to reimplement the feature computation in pure R, C or C++.
This is a collection thread for all features.

**Comment by kerschke** [comment]
When reimplementing those features, one could/should check whether they are also able to handle instances with EDGE_WEIGHT_TYPE = ATT.

**Comment by jakobbossek** [comment]
Added k-NN graph features.

**Comment by jakobbossek** [comment]
Going to check PR from @kerschke soon.

**Comment by jakobbossek** [comment]
Merge PR via 532be6b.
🎉 🎈
