### ISSUE TITLE
Bug: runtime failed: Contains missing values (element 4)

### ISSUE THREAD

**Issue by DangerN00dle** [jakobbossek/salesperson#48]
I have an issue to report. After installing the package from Github, a problem occurs, but only on Windows and Ubuntu (Mac OS Works):

>x = generateClusteredNetwork(n.points = 200L, n.cluster = 3L)
>res = runSolver("nn", x)

>Loading required package: TSP
>Error in makeTSPSolverResult(instance.name = if (testClass(instance, "Network")) instance$name else basename(instance), :
>Assertion on 'runtime' failed: Contains missing values (element 4).

After checking the system runtime by using:

>start.time = proc.time()
>Sys.sleep(1)
>as.numeric(proc.time() - start.time)

I got following result:
> [1] 0.00 0.00 1.34   NA   NA

After commenting the line 56 in the local file makeTSPSolverResult.R the local installed package works.

System tested:

Windows & Ubuntu Linux 
R Versions: 3.5.0, 3.5.1, 3.5.3, 3.6.3, 4.0.0 (I tried here a lot)
RStudio Version: 1.2.5042

I have to work with the package for a project, so if you have any questions or need more information, please feel free to ask me. It is in my own interest to help you, so do not hesitate 😃  

Cheers

**Comment by jakobbossek** [comment]
Hi, thanks for the report.
The documentation of `proc.time()` says: "... Times of child processes are not available on Windows and will always be given as NA. ..." OK, I will this soon.

**Comment by jakobbossek** [comment]
Fixed via fcd22b7
